-- local M = {}
--
-- local default_options = { noremap = true, silent = true }
--
-- function M.call(mapping)
--     -- NB!: it is important to remove items in reverse order to avoid shifting
--     local cmd = table.remove(mapping, 3)
--     local desc = table.remove(mapping, 2)
--     local key = table.remove(mapping, 1)
--
--     local mode = mapping["mode"]
--
--     mapping["mode"] = nil
--     mapping["desc"] = desc
--
--     local options = vim.tbl_extend("force", default_options, mapping)
--
--     vim.keymap.set(mode, key, cmd, options)
-- end
--
-- return M
