live_config_reload = true

[colors.bright]
black = "0x9893a5"
blue = "0x56949f"
cyan = "0xe18405"
green = "0x286983"
magenta = "0x907aa9"
red = "0xb4637a"
white = "0x575279"
yellow = "0xe18405"

[colors.cursor]
cursor = "0xcecacd"
text = "0x575279"

[colors.hints.end]
background = "#fffaf3"
foreground = "#9893a5"

[colors.hints.start]
background = "#fffaf3"
foreground = "#797593"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "0xf2e9e1"
blue = "0x56949f"
cyan = "0xe18405"
green = "0x286983"
magenta = "0x907aa9"
red = "0xb4637a"
white = "0x575279"
yellow = "0xe18405"

[colors.primary]
background = "0xfafaf7"
foreground = "0x575279"

[colors.selection]
background = "0xdfdad9"
text = "0x575279"

[colors.vi_mode_cursor]
cursor = "0xcecacd"
text = "0x575279"

[cursor]
style = "Underline"
unfocused_hollow = true

[font]
size = 19.0

[font.bold]
family = "SauceCodePro Nerd Font Mono"
style = "Bold"

[font.italic]
family = "SauceCodePro Nerd Font Mono"
style = "MediumItalic"

[font.normal]
family = "SauceCodePro Nerd Font Mono"
style = "Medium"

[font.offset]
x = 0
y = 0

[scrolling]
history = 20000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
args = ["-l"]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_padding = false
startup_mode = "Maximized"

[window.padding]
x = 10
y = 0
